apache/commons-rng

.travis.yml
pom.xml

Another PR for: https://issues.apache.org/jira/browse/RNG-11

RNG-11: refactor such that coveralls uses jacoco instead of cobertura

---

.travis.yml
pom.xml
src/main/resources/spotbugs/spotbugs-exclude-filter.xml

As per the discussion in [1], FindBugs has been discontinued, and
SpotBugs has taken its place.
This patch updates the Commons RNG project to use SpotBugs
accordingly.
[1] http://mail-archives.apache.org/mod_mbox/commons-dev/201802.mbox/raw/%3C4131eded52b31d3c9114fa5cbae48c4a%40scarlet.be%3E/
spotbgus

Replace FindBugs with SpotBugs

---

commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/LargeMeanPoissonSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/SmallMeanPoissonSampler.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/DiscreteSamplersList.java

The algorithms for small mean and large mean have been separated into
dedicated classes. Caching of constants used in the algorithm has been
used to increase speed.
Note: I have run `mvn clean verify` within the `commons-rng-sampling` module but the randomness of the `ContinuousSamplerParametricTest` causes it to fail on different distributions. I have seen failures on:
- Box-Muller Gaussian deviate
- org.apache.commons.math3.distribution.LevyDistribution (inverse method)
These are unrelated to the PoissonSampler.
I ran `mvn clean verify -DskipTests=true` and that had no errors. 
No checkstyle errors in the project files modified in this PR.

Improvement rng 50

---

commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/distribution/PoissonSamplerCachePerformance.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/LargeMeanPoissonSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/PoissonSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/PoissonSamplerCache.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/LargeMeanPoissonSamplerTest.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/PoissonSamplerCacheTest.java

RNG-51: Added a PoissonSamplerCache that exploits the fact that the state of the LargeMeanPoissonSampler is constant for all means in the range `n <= mean < n+1` where `n` is the floor of the mean.
A JMH speed test has been added to show the expected performance benefit for single-use Poisson samples.

Improvement rng 51

---

commons-rng-core/src/main/java/org/apache/commons/rng/core/source32/IntProvider.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source64/LongProvider.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/ProvidersCommonParametricTest.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source32/IntProviderTest.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source64/LongProviderTest.java
pom.xml

This PR contains the suggested changes to implement a cache to speed up the `nextInt` and `nextBoolean` methods in the core provider implementations.
These changes improve performance but the effect on the `nextInt` method of `LongProvider` is unknown. A repeat of the DieHarder and TestU01 test suites is currently in progress.

RNG-57: Cache values for provision of nextBoolean and nextInt

---

commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/distribution/PoissonSamplerCachePerformance.java

Noticed this JDK 1.8 annotation when compiling on a machine with Open JDK 1.7 (it broke).
The pom.xml for commons-rng-examples uses 1.7 as the compliance level so this should be removed. The interface is not used with Lambda expressions anyway, i.e. the annotation should not be there.

fix: removed 1.8 annotation to ensure 1.7 compliance

---

commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/CombinationSampler.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/CombinationSamplerTest.java

Complements the PermutationSampler as the sample order is C(n, k) rather
than P(n, k). Can be used for faster subset sampling if the subset order
is not important.

RNG-62: Added a CombinationSampler

---

commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/AhrensDieterMarsagliaTsangGammaSampler.java

I moved the toString() method to the internal class as this holds the reference to the RNG.
Note: The rearrangement to private classes is hard to follow in the diff view. The formatting passes the Checkstyle checks.

RNG-68: Add private classes for each algorithm

---

commons-rng-examples/examples-stress/pom.xml
commons-rng-examples/examples-stress/src/main/java/org/apache/commons/rng/examples/stress/IntGeneratorsList.java
commons-rng-examples/examples-stress/src/main/java/org/apache/commons/rng/examples/stress/LongGeneratorsList.java
commons-rng-examples/examples-stress/stress_test.md

A simple set of instructions has been added for how to build a jar file that can be used run the stress tests. This applies to the Linux platform.
Extra list classes were added to allow only the Int or Long providers to be run in the stress test.

RNG-67: Instructions for how to build and run the examples-stress code

---

commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/distribution/GeometricSamplersPerformance.java
commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/distribution/SamplersPerformance.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/GeometricSampler.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/DiscreteSamplersList.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/GeometricSamplerTest.java

This outperforms using the InverseTransformDiscreteSampler with an
appropriate Geometric inverse cumulative probability function. A JMH
benchmark has been added to demonstrate the performance.

RNG-69: Added a Geometric sampler

---

commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/AhrensDieterExponentialSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/AhrensDieterMarsagliaTsangGammaSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/BoxMullerGaussianSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/BoxMullerLogNormalSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/ChengBetaSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/GaussianSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/InverseTransformParetoSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/LargeMeanPoissonSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/LogNormalSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/SmallMeanPoissonSampler.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/AhrensDieterExponentialSamplerTest.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/AhrensDieterMarsagliaTsangGammaSamplerTest.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/BoxMullerGaussianSamplerTest.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/BoxMullerLogNormalSamplerTest.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/ChengBetaSamplerTest.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/ContinuousUniformSamplerTest.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/DiscreteUniformSamplerTest.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/GaussianSamplerTest.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/GeometricSamplerTest.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/InverseTransformParetoSamplerTest.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/LargeMeanPoissonSamplerTest.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/LogNormalSamplerTest.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/RejectionInversionZipfSamplerTest.java

This adds checks matching those found in the commons-math3 distributions
to the samplers. An additional check missing in commons-math3 was added to the `LogNormalSampler` to ensure the mean (scale) parameter was positive. I am unsure why this check is missing in CM as it is defined here [Log-normal_distribution](https://en.wikipedia.org/wiki/Log-normal_distribution).
The existing validation checks in the PoissonSampler
have had their exception messages changed for consistency across all the samplers.
A test for
the ContinuousUniformSampler was added to demonstrate no range checks
are required.

RNG-71: Validate parameters for the distribution samplers

---

README.md
commons-rng-client-api/README.md
commons-rng-core/README.md
commons-rng-examples/README.md
commons-rng-examples/examples-jmh/README.md
commons-rng-examples/examples-jpms/README.md
commons-rng-examples/examples-jpms/jpms-app/README.md
commons-rng-examples/examples-jpms/jpms-lib/README.md
commons-rng-examples/examples-quadrature/README.md
commons-rng-examples/examples-sampling/README.md
commons-rng-examples/examples-stress/README.md
commons-rng-sampling/README.md
commons-rng-simple/README.md

All Javadoc links are now valid where appropriate.
Manual edits were made on the build plugin output to support the sub-modules.

Update readme using commons-build-plugin

---

commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/CollectionSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/CombinationSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/DiscreteProbabilityCollectionSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/ListSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/PermutationSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/SubsetSamplerUtils.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/UnitSphereSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/AhrensDieterExponentialSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/AhrensDieterMarsagliaTsangGammaSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/BoxMullerGaussianSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/BoxMullerLogNormalSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/BoxMullerNormalizedGaussianSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/ChengBetaSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/ContinuousUniformSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/DiscreteUniformSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/GeometricSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/InverseTransformContinuousSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/InverseTransformDiscreteSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/InverseTransformParetoSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/LargeMeanPoissonSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/MarsagliaNormalizedGaussianSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/PoissonSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/PoissonSamplerCache.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/RejectionInversionZipfSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/SmallMeanPoissonSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/ZigguratNormalizedGaussianSampler.java

This adds details to the javadoc for the samplers describing the method(s) used from {{UniformRandomProvider}}.
I added missing </p> tags for consistency through the javadoc for the package.

RNG-73: Add methods used from UniformRandomProvider to the samplers.

---

commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/ThreadLocalPerformance.java
commons-rng-simple/src/main/java/org/apache/commons/rng/simple/ThreadLocalRandomSource.java
commons-rng-simple/src/test/java/org/apache/commons/rng/simple/ThreadLocalRandomSourceTest.java

Please review.
This add functionality to store a `ThreadLocal<UniformRandomProvider>` for each enum in `RandomSource`. This is seeded using the default seeding provided by `RandomSource.create(RandomSource)`.

RNG-78: Added a ThreadLocalRandomSource.

---

commons-rng-core/src/main/java/org/apache/commons/rng/core/util/NumberFactory.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/util/NumberFactoryTest.java

This changes the nextFloat/nextDouble methods to use an extra bit of
state from the underlying int or long primitive.

RNG-81: NumberFactory to sample all rationals between 0 and 1.

---

commons-rng-core/src/main/java/org/apache/commons/rng/core/source32/MersenneTwister.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source64/MersenneTwister64.java
commons-rng-examples/examples-jpms/pom.xml
pom.xml

This fix allows:
`mvn clean package site`
to work on JDK 8 and 11.
`mvn clean package site -P commons-rng-examples`
does not work. Javadoc generation fails for the JPMS modules. The javadoc tool complains about links to a Javadoc API in the unamed modules:
```
The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/9/docs/api/ are in the unnamed module.
```
This javadoc issue when building using JDK 11 for a source earlier than 11 is found in a lot of web posts. The fix that works for a source earlier than 9 (i.e. using the `<source>7</source>` tag in the maven javadoc configuration) does not work when the source is 9 and has modules.
One simple workaround is to not use JDK 11 to build javadocs.

Jdk 11 build

---

commons-rng-core/src/main/java/org/apache/commons/rng/core/source32/MultiplyWithCarry256.java

This avoids an `if` statement check and marginally improves performance (see the Jira ticket [RNG-87](https://issues.apache.org/jira/browse/RNG-87)).
It has the advantage of not advancing the state further ahead than necessary.

RNG-87: Advance MultiplyWithCarry256 state one index per nextInt() call.

---

commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/AbstractBenchmark.java
commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/BaselineGenerationPerformance.java
commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/BaselineSources.java
commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/BaselineUtils.java
commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/FloatingPointGenerationPerformance.java
commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/NextBooleanGenerationPerformance.java
commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/NextBytesGenerationPerformance.java
commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/NextDoubleGenerationPerformance.java
commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/NextFloatGenerationPerformance.java
commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/NextIntGenerationPerformance.java
commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/NextLongGenerationPerformance.java

The baseline is a minimal implementation that can be used to subtract
the timing overhead of JMH from the results.
Note: This renames the existing NextDoublePerformance to
FloatingPointGenerationPerformance. This avoids confusion with the
new baseline benchmarks.

RNG-88: Baseline the generation performance benchmark.

---

commons-rng-core/src/main/java/org/apache/commons/rng/core/source32/AbstractXoRoShiRo64.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source32/AbstractXoShiRo128.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source32/XoRoShiRo64Star.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source32/XoRoShiRo64StarStar.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source32/XoShiRo128Plus.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source32/XoShiRo128StarStar.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source64/AbstractXoRoShiRo128.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source64/AbstractXoShiRo256.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source64/AbstractXoShiRo512.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source64/XoRoShiRo128Plus.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source64/XoRoShiRo128StarStar.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source64/XoShiRo256Plus.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source64/XoShiRo256StarStar.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source64/XoShiRo512Plus.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source64/XoShiRo512StarStar.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/ProvidersList.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source32/XoRoShiRo64StarStarTest.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source32/XoRoShiRo64StarTest.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source32/XoShiRo128PlusTest.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source32/XoShiRo128StarStarTest.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source64/XoRoShiRo128PlusTest.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source64/XoRoShiRo128StarStarTest.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source64/XoShiRo256PlusTest.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source64/XoShiRo256StarStarTest.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source64/XoShiRo512PlusTest.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source64/XoShiRo512StarStarTest.java
commons-rng-simple/src/main/java/org/apache/commons/rng/simple/RandomSource.java
commons-rng-simple/src/main/java/org/apache/commons/rng/simple/internal/ProviderBuilder.java
commons-rng-simple/src/test/java/org/apache/commons/rng/simple/ProvidersList.java
src/changes/changes.xml

Please review.
Generators have been created to match their reference implementation. 
This change incorporates modification of the existing ``XorShift1024Star`` class to enable the slightly different ``XorShift1024StarPhi``to inherit all functionality. That change can be moved to a diffferent PR if required.
The design moves common code for save/restore to abstract classes. However the amount of code is small and the abstract classes could be dropped is favour of code duplication to reduce the number of extra abstract classes.
If a seed is provided with all zeros then the generators are broken. A test asserts that this is allowed.
I have only modified the projects core and simple. Further changes to the other projects to add the extra providers will be required when accepted.

RNG-70: Add new XoShiRo generators

---

commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/distribution/PoissonSamplersPerformance.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/KempSmallMeanPoissonSampler.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/DiscreteSamplersList.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/KempSmallMeanPoissonSamplerTest.java

Add a benchmark to the JMH examples of various methods to compute a Poisson sample.
This sampler is suitable for use an alternative to the SmallMeanPoissonSampler when the generator is slow. Speed at mean <1 is comparable. At mean in the range 1-40 a slow generator would favour this method, a fast generator would favour the SmallMeanPoissonSampler.

RNG-91: Added a KempSmallMeanPoissonSampler

---

commons-rng-core/src/main/java/org/apache/commons/rng/core/util/NumberFactory.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/util/NumberFactoryTest.java
src/changes/changes.xml

Changes the methods to read and write directly from the input / output
arrays avoiding creating an intermediate small array.
Additional tests were added to the `NumberFactoryTest` to ensure functionality was unchanged and the endian byte order of input/output arrays was maintained as documented in the method description.

RNG-77: Improve NumberFactory to/from byte arrays performance.

---

commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/LargeMeanPoissonSampler.java

The Kemp sampler has more stable performance at mean less than 1 than the SmallMeanPoissonSampler.

RNG-103: Use KempSmallMeanPoissonSampler in LargeMeanPoissonSampler.

---

pom.xml

Removed versions superseded by the parent POM.
Downgrade JXR from parent-48 v3.0.0 to 2.5 for multi-module site build.
This builds on Java 9 using:
`mvn -Pcommons-rng-examples clean package site site:stage`

Upgrade parent to 48.

---

.travis.yml
pom.xml

This is a test PR to see if an updated coverage/travis configuration is OK. The update is to run the default Maven goal. This adds apache-rat:check and javadoc:javadoc goals to those currently tested.
It removes the customisation of the jacoco coverage rules so that the commons parent is used. This makes the checks stricter but coverage is high so this is fine.
Previously checks were performed in the after_success phase which is allowed to fail. Thus if checks failed then this would be lost and checks had no effect on reporting bad PRs. This updates to run the default maven goal with all checks. If successful then coverage reports will be submitted.
A profile has been added to disable checks in the JDK 7 build as this uses plugins that require JDK 8.

Update travis build

---

commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/distribution/DiscreteUniformSamplerGenerationPerformance.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/DiscreteUniformSampler.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/DiscreteSamplersList.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/DiscreteUniformSamplerTest.java

Algorithms are added for ranges that are a power of 2 and non-power of 2.
Now specifically handles a lower bound of 0.
The algorithm for a non-power of two precomputes a rejection threshold then avoids the modulus operator during sampling. This can significantly increase speed when the rejection rate is expected to be high.

RNG-95: Update the DiscreteUniformSampler using faster algorithms.

---

commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/distribution/EnumeratedDistributionSamplersPerformance.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/DiscreteProbabilityCollectionSampler.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/DiscreteProbabilityCollectionSamplerTest.java
src/changes/changes.xml

The sampler has been updated to use a GuideTableDiscreteSampler as an internal delegate.
A benchmark is included to show performance of different samplers on various probability distributions.

RNG-109: DiscreteProbabilityCollectionSampler to use an internal DiscreteSampler

---

commons-rng-core/src/main/java/org/apache/commons/rng/core/source32/JDKRandom.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source32/JDKRandomTest.java
commons-rng-simple/src/main/java/org/apache/commons/rng/simple/JDKRandomWrapper.java
commons-rng-simple/src/test/java/org/apache/commons/rng/simple/JDKRandomWrapperTest.java
src/changes/changes.xml

This can wrap a SecureRandom instance to provide access to the
underlying OS source of randomness when on a supported platform.

RNG-19: Create a wrapper for JDK Random.

---

commons-rng-core/src/main/java/org/apache/commons/rng/core/source32/JDKRandom.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source32/JDKRandomTest.java

Save the state size to the byte array representation. This can be read
by any instance when restoring.

RNG-115: Fix JDKRandom to restore state to a new instance.

---

commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/ContinuousSamplerParametricTest.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/DiscreteSamplerParametricTest.java

Only 1 re-run is allowed and the number of samplers is high enough that
spurious failures are realistic for the samplers.
Changed the Continuous samplers failure rate from p=0.0138 to p=0.0016.
This is an effective change of numFailures(n=50, p=0.01) > 2 to
numFailures(n=50, p=0.01) > 3.
Changed the Discrete samplers failure rate from p=0.0000189 to p=0.0016
to match the continuous samplers test. Each test is now assessed at the
p=0.01 level not the p=0.001 level. This is an effective change of
numFailures(n=50, p=0.001) > 2 to numFailures(n=50, p=0.01) > 3.

Changed samplers parametric test failure probability.

---

commons-rng-core/src/main/java/org/apache/commons/rng/core/source32/AbstractXoShiRo128.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source64/AbstractXoShiRo512.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/RandomAssert.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source32/XoShiRo128PlusTest.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source32/XoShiRo128StarStarTest.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source64/XoShiRo512PlusTest.java
commons-rng-core/src/test/java/org/apache/commons/rng/core/source64/XoShiRo512StarStarTest.java
commons-rng-simple/src/test/java/org/apache/commons/rng/simple/RandomSourceTest.java

This adds the long jump function to those generators previously
supporting only a jump function.

RNG-119: Add LongJumpable support to XoShiRo generators.

---

commons-rng-core/src/main/java/org/apache/commons/rng/core/source32/AbstractPcg6432.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source32/PcgXshRr32.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source32/PcgXshRs32.java
commons-rng-core/src/main/java/org/apache/commons/rng/core/source64/PcgRxsMXs64.java

Use of the 128-bit constructor may exhibit large correlations in output
of different streams. Notes have been added to the javadoc header and
the 128-bit constructors.

[RNG-123] Document PCG generators potential stream correlation

---

commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/sampling/UnitSphereSamplerBenchmark.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/UnitSphereSampler.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/UnitSphereSamplerTest.java
src/changes/changes.xml

RNG-129:
- Add a benchmark for specialisations for low dimensions.
- Implement specialistions for 1D, 2D and 3D. 
- Use a delegate in a publicly constructed UnitSphereSampler.
RNG-130:
- Fix 1 dimension sampling to only return vectors containing 1 or -1.

RNG-129: Improve performance of UnitSphereSampler

---

commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/sampling/shape/TetrahedronSamplerBenchmark.java
commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/sampling/shape/TriangleSamplerBenchmark.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/CollectionSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/CombinationSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/DiscreteProbabilityCollectionSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/ObjectSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/PermutationSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/SharedStateObjectSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/UnitSphereSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/shape/BoxSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/shape/LineSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/shape/TetrahedronSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/shape/TriangleSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/shape/UnitBallSampler.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/UnitSphereSamplerTest.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/shape/BoxSamplerTest.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/shape/LineSamplerTest.java
src/changes/changes.xml

Add generic ObjectSampler interfaces. These are the object typed equivalent to the DiscreteSampler and SharedStateDiscreteSampler interfaces (which return samples of int).
Deprecate the UnitSphereSampler.nextVector method. It is replaced by the
ObjectSampler.sample method.

RNG-136: Add ObjectSampler<T> and SharedStateObjectSampler<T> interfaces

---

commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/LongSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/SharedStateLongSampler.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/UniformLongSampler.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/RandomAssert.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/UniformLongSamplerTest.java

This is replacement for RandomUtils.nextLong(long lo, long hi) from
Commons Math.

RNG-140: Add LongSampler interface and UniformLongSampler

---

commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/sampling/distribution/ContinuousSamplersPerformance.java
commons-rng-examples/examples-jmh/src/main/java/org/apache/commons/rng/examples/jmh/sampling/distribution/StableSamplerPerformance.java
commons-rng-sampling/src/main/java/org/apache/commons/rng/sampling/distribution/StableSampler.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/ContinuousSamplersList.java
commons-rng-sampling/src/test/java/org/apache/commons/rng/sampling/distribution/StableSamplerTest.java
src/main/resources/checkstyle/checkstyle-suppressions.xml
src/main/resources/pmd/pmd-ruleset.xml
src/main/resources/spotbugs/spotbugs-exclude-filter.xml

Re-implemented the StableRandomGenerator from Commons Math random
package.
Uses a translation of the Fortran RSTAB program from Chambers et al
(1976).
Add a JMH benchmark to demonstrate speed of the RSTAB routine verses a
alternative implementation that is discontinuous as alpha approaches 1.
The sampler checks the distribution support and corrects invalid
samples.
Uses a fast tan(x) / x function approximation.

RNG-137: Add StableSampler

---

commons-rng-client-api/src/main/java/org/apache/commons/rng/SplittableUniformRandomProvider.java
commons-rng-client-api/src/main/java/org/apache/commons/rng/UniformRandomProviderSupport.java
commons-rng-client-api/src/test/java/org/apache/commons/rng/BaseRandomProviderStreamTest.java
commons-rng-client-api/src/test/java/org/apache/commons/rng/SplittableUniformRandomProviderStreamTest.java
commons-rng-client-api/src/test/java/org/apache/commons/rng/SplittableUniformRandomProviderTest.java
commons-rng-client-api/src/test/java/org/apache/commons/rng/UniformRandomProviderStreamTest.java
commons-rng-client-api/src/test/java/org/apache/commons/rng/UniformRandomProviderTest.java
src/changes/changes.xml
src/main/resources/checkstyle/checkstyle-suppressions.xml
src/main/resources/pmd/pmd-ruleset.xml

Provide default implementations for spliterators to support parallel
streams for the interface stream methods. This includes the parent
UniformRandomProvider interface methods for primitive streams.
Refactor stream tests for UniformRandomProvider to allow the same tests
to be used on SplittableUniformRandomProvider.

RNG-180: Add a SplittableUniformRandomProvider interface
